
version: 2

models:
    # - name: my_first_dbt_model
    #   description: "A starter dbt model"
    #   columns:
    #       - name: id
    #         description: "The primary key for this table"
    #         tests:
    #             - unique
    #             - not_null
    #
    # - name: my_second_dbt_model
    #   description: "A starter dbt model"
    #   columns:
    #       - name: id
    #         description: "The primary key for this table"
    #         tests:
    #             - unique
    #             - not_null




    - name: users_categorycount
      columns:
          - name: user_id
            tests:
              - relationships:
                  to: ref('users_topcat')
                  field: user_id

    - name: combined_order_products
      description: "combined product order table"
      tests:
        - unique:
            column_name: "(order_id || '-' || product_id)"
        - not_null:
            column_name: "(order_id || '-' || product_id)"
        # - accepted_values:
        #     column_name: order_hour_of_day
        #     values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]

        # - relationships:
        #     column_name: ""
        #       to: ref('customers')
        #       field: id


sources:
  - name: insta_data_set
    tables:
      - name: aisles
      - name: departments
      - name: orders
      - name: products
      - name: order_products_train
      - name: order_products_prior
