
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null


sources:
  - name: insta_data_set
    tables:
      - name: aisles
      - name: departments
      - name: orders
      - name: products
      - name: order_products_train
      - name: order_products_prior
